language: node_js
node_js:
   - '8'

before_script:
   - npm install -g @angular/cli

script:
   - ng build --prod --aot

deploy:
  provider: pages
  skip_cleanup: true
  target_branch: master
  fqdn: laserflash.tk
  on:
    branches:
      only:
         - webDev
