language: node_js
node_js:
   - '8'

branches:
   only:
      - webDev

before_script:
   - npm install -g @angular/cli

script:
   - ng build --prod --aot

deploy:
  provider: pages
  skip_cleanup: true
  on:
    branch: master
