language: node_js
node_js:
   - '8'

before_script:
   - npm install -g @angular/cli

script:
   - ng build --prod --aot

deploy:
  provider: pages
  skip_cleanup: true
  target_branch: master
  fqdn: laserflash.tk
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: webDev
